### ISSUE TITLE
Calendar new features

### ISSUE THREAD

**Issue by noDGodyaev** [dkagramanyan/eventer-psvt21#12]
Чеклист всяких календарных штук ниже. @dkagramanyan, добавь что-то если посчитаешь нужным.
Преамбула:
Исходные данные - excel таблица (google sheets)
Обработка - скрипт, привязанный к таблице (js + google APIs)
Планируемый результат - каждый участник посвята получает личное приглашение в именной гугл календарь, который будет отражать последовательность событий описанных в таблице.

Актуальный чеклист
- [x] Подключение к календарям и таблице
     - [x] Реализовать в виде отдельной функции
- [x]  Составить перечень правил составления таблицы - оформить в виде readme
- [x]  Реализовать парсер согласно установленным правилам
     - [x] Реализовать в виде отдельной функции
- [x]  Формирование одного события календаря из нескольких одинаковых ячеек таблицы
     - [x] Дополнение к правилам составления таблицы
- [x]  Предоставление пользователям индивидуального доступа к календарю 
- [x]  Перенос цвета из таблицы в календарь с условием ограничения количества цветов календаря   
- [x]  Обработка исключений: создание копий календарей при перезапуске скрипта
- [x]  Обработка исключений: дублирование событий при перезапуске скрипта
- [x]  Обработка исключений: приглашения пользователям отправляются при каждом запуске скрипта
- [ ]  Разделить функционал на:
     - [ ]  создание календарей
     - [ ]  чистка календарей и их заполнение данными из excel таблицы
     - [ ]  шеринг календарей с пользователями (принцип работы - собираем при помощи гугл формы данные пользователей в формате фи-почта, затем на основе фи ведем поиск по созданным календарям )
- [x]  Инициализировать имена календарей (при их создании) заготовленными фи (пример: изначально задаем список фи, а затем каждому человеку создаем календарь)
- [x] добавить парсеру отдельную ячейку с датой создания календарей 
- [ ] пофиксить отображение событий у расшаренного календаря (почему-то нормально шерится только мемная почта, остальные брухаются)
- [ ] сделать шеринг календаря при каждом запуске скрипта
- [ ] написать функцию для удаления ранее созданных календарей
- [ ] добавить "флаг" для динамической индикации того, созданы ранее календари или нет
- [ ] шерить календари после их заполнения

Будущая работа

- [ ] Улучшить метрику для сравнения цветов 
- [x] Добавить кнопку для запуска скрипта

**Comment by dkagramanyan** [comment]
- [ ] 
     - [ ]

**Comment by dkagramanyan** [comment]
- [ бла, бла]

**Comment by dkagramanyan** [comment]
- [ x] бла бла

**Comment by dkagramanyan** [comment]
@noDGodyaev, добавил несколько пунктов
