### ISSUE TITLE
Bot schedule display

### ISSUE THREAD

**Issue by dkagramanyan** [dkagramanyan/eventer-psvt21#15]
@DenZeDi 

Актуальный чеклист
- [x] Вывод всех событий в функции запроса расписания
- [x]  Создание класса бота с характеристиками:
     - [x] один из атрибутов класса - connection к бд
     - [x] используемые функции преобразовать в методы класса
- [x] создание бесконечного цикла, который перезапускал бота при его падении
- [ ] уведомление пользователя о смене точки за 5 мин
- [x] проверка на пустые запросы и на отсутствие человека в базе 
- [x] сохранить chat id в бд
- [x] сделать систему авторизации (Как вас зовут? Фамилия? "сохраняет chat id")
- [x] ограничители для пользователей + фамилия и имя
- [ ] парсер данных и заполнение бд

**Comment by dkagramanyan** [comment]
@DenZeDi, да пребудет с тобой ооп и гугл

**Comment by DenZeDi** [comment]
Хахахах, хорошо, задачи принял))
