### ISSUE TITLE
Google Calendar local script

### ISSUE THREAD

**Issue by dkagramanyan** [dkagramanyan/eventer-psvt21#17]
@TheMostKnown 

Актуальный чеклист:
- [ ] Создание календарей. Название календаря - Имя пользователя (например, Пупа Бобович)
- [ ] Загрузка календарей пользователей их событиями из расписания (бд). Событие - название, время начала/конца 
- [ ] Очистка календарей
- [ ] Изменение определенного события у пользователя
- [ ] Изменение онлайн гугл таблицы с расписанием при изменении расписания в бд

**Comment by dkagramanyan** [comment]
@TheMostKnown, у события есть какой-то id? Он нужен для того, чтобы бот мог найти это событие и изменить его характеристики

**Comment by TheMostKnown** [comment]
> @TheMostKnown, у события есть какой-то id? Он нужен для того, чтобы бот мог найти это событие и изменить его характеристики

Сейчас по документации посмотрел, поле такое присутствует
